- name: Install ansible and download my playbooks for system management
  hosts: all
  vars:
    ansible_setup_path: "{{ ansible_env.HOME }}/src/ansible-system-setup"
  tasks:
      # Ansible from official repos is ancient - use PPA
    - name: add ansible PPA
      apt_repository:
        repo: ppa:ansible/ansible
      become: yes

    - name: install latest Ansible
      apt: name=ansible state=latest
      become: yes

    - name: create directory for roles from ansible galaxy
      file: path=/etc/ansible/roles state=directory
      become: yes

    - name: create directory for ansible plugins
      file: path=/usr/share/ansible_plugins/{{ item }} state=directory
      with_items:
        - callback_plugins
        - vars_plugins
        - lookup_plugins
      become: yes

    - name: download ansible-profile plugin
      # I don't use get_url module because it's slower.
      command: >
        wget https://raw.githubusercontent.com/jlafon/ansible-profile/master/callback_plugins/profile_tasks.py
        chdir=/usr/share/ansible_plugins/callback_plugins/
        creates=/usr/share/ansible_plugins/callback_plugins/profile_tasks.py
      become: yes
      
    - name: clone ansible-system-setup repository
      git: 
        repo=https://github.com/jan-warchol/ansible-system-setup/
        dest="{{ ansible_setup_path }}"
        version=devel
      register: task_result
      failed_when: task_result | failed and "Local modifications exist in repository" not in task_result.msg

    - name: update ansible-system-setup remote
      lineinfile:
        dest: "{{ ansible_setup_path }}/.git/config"
        regexp: url = .*ansible-system-setup
        line: "	url = git@github.com:jan-warchol/ansible-system-setup.git"

      # I don't want to accidentally commit something with my work email.
    - name: override git authorship setting in ansible-system-setup
      blockinfile:
        dest: "{{ ansible_setup_path }}/.git/config"
        block: |
          [user]
            name = Jan Warchoł
            email = jan.warchol@gmail.com
      # don't use "inventory_hostname in groups.xxx" construct
      # because it fails when group xxx is not defined.  This is better.
      when: "'work_computers' in group_names"
