- hosts: all
  vars:
    pass_gpg_key_fingerprint: "EC5E 11DD EF42 BF79 FBFA 4F4E FF6A DDEB B33A 5D2F" 
    key_filename: "GPG_key_{{ pass_gpg_key_fingerprint | replace(' ', '') }}.asc"

  roles:
    - known-hosts

  tasks:

    - name: ensure directories exist
      file:
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        mode: 0700
      loop:
        - .ssh
        - .gnupg

    - name: copy personal ssh key
      copy:
        dest: "{{ ansible_env.HOME }}/.ssh/id_rsa_personal_2c6819cb"
        content: "{{ lookup('passwordstore', 'personal-ssh-key returnall=true') }}"
        mode: 0600
      no_log: true

    - name: copy GPG key for password store
      copy:
        dest: "{{ ansible_env.HOME }}/.gnupg/{{ key_filename }}"
        content: "{{ lookup('passwordstore', 'personal-gpg-key returnall=true') }}"
        mode: 0600
      no_log: true

    - name: import gpg key
      command: gpg2 --batch --import {{ ansible_env.HOME }}/.gnupg/{{ key_filename }}

    - name: clone password store
      git:
        repo: git@bitbucket.org:jan-warchol/password-store.git
        dest: "{{ ansible_env.HOME }}/.password-store"
        key_file: "{{ ansible_env.HOME }}/.ssh/id_rsa_personal_2c6819cb"
