- hosts: localhost
  become: yes
  tasks:

    # FIXME
    # Ansible's apt_repository module doesn't work correcty with Linux Mint,
    # see https://github.com/ansible/ansible/issues/4587
    # Also, the filenames that are checked for existence are hardcoded :(

    - name: Add FreeFileSync PPA
      command: >
        add-apt-repository --yes ppa:freefilesync/ffs
        creates=/etc/apt/sources.list.d/freefilesync-ffs-trusty.list
      register: ffs_ppa_status

    #- name: FreeFileSync wasn't available in Utopic Unicorn repos
    #  shell: sed -i 's/utopic/trusty/' /etc/apt/sources.list.d/freefilesync*

    - name: update apt cache
      apt: update_cache=yes
      when: ffs_ppa_status.changed

    - name: Install latest versions of apt packages
      apt:
        name: "{{ item }}"
        state: latest
        install_recommends: no
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - baobab
        - dconf-cli
        - dconf-editor   # desktop environment configuration
        - firefox   # make sure firefox is updated - my package manager
                    # didn't want to update it on its own
        - freefilesync
        - gitk
        - gparted
        - indicator-multiload
        - kate
        - keepass2
        - xdotool   # library for auto-type in keepass
        - libdvdread4   # DVD decryption
          # at least one of these 3 packages is needed for okular to open pdfs
        - kdelibs5-plugins
        - kdelibs5-data
        - oxygen-icon-theme
        - okular
        - openjdk-7-jre
        - terminator
        - vim-gnome
        - vlc
        - xbacklight   # changing screen brightness
        - xsel   # copying and pasting from middle-mouse-button clipboard
        #- gimp
        #- guake
        #- imagemagick
        #- kompare

