- hosts: all
  become: yes
  tasks:

    - name: Install latest versions of apt packages
      apt:
        name: "{{ item }}"
        state: latest
        install_recommends: no
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - baobab
        - dconf-cli
        - dconf-editor   # desktop environment configuration
        - firefox   # make sure firefox is updated - my package manager
                    # didn't want to update it on its own
        - gitk
        - gparted
        - indicator-multiload
        - kate
        - keepass2
        - xdotool   # library for auto-type in keepass
        - libdvdread4   # DVD decryption
          # at least one of these 3 packages is needed for okular to open pdfs
        - kdelibs5-plugins
        - kdelibs5-data
        - oxygen-icon-theme
        - okular
        - openjdk-7-jre
        - terminator
        - vim-gnome
        - vlc
        - xbacklight   # changing screen brightness
        - xsel   # copying and pasting from middle-mouse-button clipboard
        #- gimp
        #- guake
        #- imagemagick
        #- kompare

